#!/usr/bin/env bash

KEYPATH="$HOME/.ssh/id_rsa"

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo -e "\n>>> Installing Pip\n" 
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
fi

python3 get-pip.py
pip3 install pipreqs

# install dependencies
pip install -r requirements.txt

echo -e "\n>>> Generating SSH keys\n"

ssh-keygen -t rsa
sleep 1
echo $KEYPATH

ssh-copy-id -i $HOME/.ssh/id_rsa.pub $HOST ~/.ssh/id_rsa

# Test SSH connection
ssh $HOST

if [ $? -eq 0 ]; then
    echo -e "\nSSH connection successful.\n"
fi
