#!/usr/bin/env bash

if [[ "$OSTYPE" == "darwin"* ]]; then
  brew install expect
  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
fi


python3 get-pip.py
pip3 install pipreqs

# install dependencies
pip install -r requirements.txt

ssh-keygen -t rsa
