# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerDownDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from generateScript import GenerateScript


class Ui_power_dialogBox(object):
    def __init__(self, obj):
        self.gs = obj
        power_dialogBox = QtWidgets.QMainWindow()
        self.setupUi(power_dialogBox)
        self.retranslateUi(power_dialogBox)

    def setupUi(self, power_dialogBox):
        power_dialogBox.setObjectName("power_dialogBox")
        power_dialogBox.resize(340, 136)
        power_dialogBox.setWindowTitle("")
        self.centralwidget = QtWidgets.QWidget(power_dialogBox)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 311, 71))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 100, 321, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        power_dialogBox.setCentralWidget(self.centralwidget)

        self.retranslateUi(power_dialogBox)
        QtCore.QMetaObject.connectSlotsByName(power_dialogBox)

    def retranslateUi(self, power_dialogBox):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("power_dialogBox", "Sarah, this will shutdown the RaspberryPi.  To turn it back on, you\'ll just have to unplug it and plug it back in...but wait about 10 seconds before unplugging. :)"))
        self.pushButton.setText(_translate("power_dialogBox", "Cancel"))
        self.pushButton_2.setText(_translate("power_dialogBox", "Ok"))
        self.pushButton.clicked.connect(power_dialogBox.close)
        self.pushButton_2.clicked.connect(self.gs.shutdownDevice)
        self.pushButton_2.clicked.connect(power_dialogBox.close)



if __name__ == "__main__":
    import sys
    gs = GenerateScript()
    app = QtWidgets.QApplication(sys.argv)
    power_dialogBox = QtWidgets.QMainWindow()
    ui = Ui_power_dialogBox(gs)
    ui.setupUi(power_dialogBox)
    power_dialogBox.show()
    sys.exit(app.exec_())
